### ISSUE TITLE
2.1 - "Regras de movimentação de peças"

### ISSUE THREAD

**Issue by VitinhoCarneiro** [FelipeLVieira/checkers-ai-software-engineering-2#9]
Implementar as regras para a validação da movimentação das peças, tanto das peças normais quanto das damas.

**Comment by phelipegm** [comment]
Olá, o que falta para fechar este item ?

**Comment by FelipeLVieira** [comment]
Realizar mais testes pra verificar se o método recursivo está retornando o vetor de movimentos possíveis corretamente.
Eu terminei de implementar a versão recursiva agora pela manhã.
Seria bom ter outra pessoa pelo menos pra testar e verificar se está funcionando corretamente e apontar ajustes necessários.

**Comment by FelipeLVieira** [comment]
Eu fiz alguns movimentos pra comer até 3 peças e ele funcionou corretamente

**Comment by phelipegm** [comment]
Blz, chegando em casa testarei esse item

**Comment by VitinhoCarneiro** [comment]
There is one change that needs to be made.

The code within GameLoop that moves a piece in the board should be put into a function in GameLoop.py. I did remark it, just search for "VitinhoCarneiro".

I need it for the AI.
